pagopa/trial-system

.github/pull_request_template.md
=> [IOPLT-459] Add pull request template

.github/CODEOWNERS
Create CODEOWNERS file.
We need to add some owners to this repository.
Syntax checks made by GitHub, visible on file diff view.
=> [IOPLT-461] Create CODEOWNERS file

.github/workflows/pr-title-linter-and-linker.yaml
Adding Github actions for linting an Jira link
- add pr-title-linter-and-linker.yaml
This PR is required to allow PR to be linked with related JIRA tickets
=> [#IOPLT-462] Add PR linter and linker

.yarnrc.yml, package.json, packages/eslint-config/eslint.config.js, packages/eslint-config/fneslint-config.js, packages/eslint-config/index.js, packages/eslint-config/package.json, packages/eslint-config/prettier-config.js, packages/eslint-config/tseslint-config.js, yarn.lock
> [!NOTE]
This project adopts the most recent version of `eslint` (9.1.1), which introduces the *flat config files* and deprecates the *eslintrc* format. For more infromation, please refer to the [documentation](https://eslint.org/docs/latest/use/migrate-to-9.0.0#-new-default-config-format-eslintconfigjs).
> [!WARNING]
Currently, the [@pagopa/eslint-rules](https://github.com/pagopa/eslint-rules) package is not integrated due to its incompatibility with the latest versions of eslint.
- A new package `eslint-config`
- Disable hoisting to ensure that each workspace declares the dependencies it uses
Add a shared rules package that will be used by both the `apps` and `packages` modules. 
Creating locally a test apps that uses the rules
=> [IOPLT-460] Add eslint-config package

.github/workflows/code_review_infra.yaml, .github/workflows/release_infra.yaml
- Add "Code Review" Infra workflow
- Add "Release Infra" workflow
We want to check the IaC automatically.
We want an automated way to deploy the Infrastructure.
=> [IOPLT-472] Add "Code Review Infra" and "Release Infra" workflows

.github/auto-assign.yaml, .github/workflows/decorate_pr.yaml, .github/workflows/enrich_pr.yaml
- Configure how to add the assignee
- Crate workflow that adds the assignee
We want to automatically add the assignee to the PR
=> [IOPLT-477] Add assignee to PR

.github/labeler.yaml, .github/workflows/enrich_pr.yaml
Depends on #12
- Define labels to add to the PR
- Add labels to PR using an existing workflow
We want to decorate the PRs using labels.
Labels could be useful to determine what's changed in the PR.
=> [IOPLT-476] Add labels to PRs

.github/workflows/code_review.yaml, package.json
- Create Code Review workflow
We want to perform some automatic checks on Pull Requests
=> [IOPLT-474] Add code review workflow

apps/functions-subscription/package.json, apps/functions-subscription/src/adapters/azure/functions/__tests__/info.test.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/mocks.ts, apps/functions-subscription/src/adapters/azure/functions/info.ts, apps/functions-subscription/src/main.ts, package.json, packages/eslint-config/fneslint-config.js, packages/eslint-config/index.js
- Update eslint rules to remove some errors on test files
- Add test for info handler
- Update `package.json` of root and of `functions-subscription` module
Enable the system to be tested adding one first test as example
Unit test (`npm run test` and `npm run test:coverage`)
=> [IOPLT-487] Add tests structure plus info handler test

.github/workflows/code_review_infra.yaml
- Update `paths` filter
The old paths didn't look at changes to any file of the directory.
With this change, any changes made to any file of the directory trigger this workflow.
=> [IOPLT-491] Fix path of code_review_infra workflow

.changeset/plenty-ducks-rush.md, apps/functions-subscription/local.settings.json.example, apps/functions-subscription/package.json, apps/functions-subscription/src/adapters/azure/cosmosdb/__tests__/mocks.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/__tests__/subscription.test.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/decode.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/errors.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/subscription.ts, apps/functions-subscription/src/adapters/azure/eventhubs/__tests__/mocks.ts, apps/functions-subscription/src/adapters/azure/eventhubs/__tests__/subscription-request.test.ts, apps/functions-subscription/src/adapters/azure/eventhubs/subscription-request.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/info.test.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/mocks.ts, apps/functions-subscription/src/adapters/azure/functions/info.ts, apps/functions-subscription/src/adapters/crypto/__tests__/hash.test.ts, apps/functions-subscription/src/adapters/crypto/hash.ts, apps/functions-subscription/src/adapters/date/clock.ts, apps/functions-subscription/src/config.ts, apps/functions-subscription/src/domain/__tests__/data.ts, apps/functions-subscription/src/domain/subscription-request.ts, apps/functions-subscription/src/domain/subscription.ts, apps/functions-subscription/src/main.ts, apps/functions-subscription/src/system-env.ts, apps/functions-subscription/src/use-cases/errors.ts, vitest.config.ts, yarn.lock
- Add cosmosdb adapter
- Add eventhub adapter
- Add clock adapter
- Add hashFn adapter
- Add config
- Update main
- Update info endpoint implementation
To run the system needs the adapters.
Unit tests.
=> [IOPLT-525] Add adapters

.changeset/cold-clouds-walk.md, apps/functions-subscription/src/main.ts
We need to authenticate calls to the `POST /trials/{trialId}/subscriptions` endpoint.
- Change `authLevel` to `function` for `createSubscription` handler.
Before this commit, `authLevel` was set to `anonymous`, which means "No API key is required".
After this commit, the `authLevel` becomes `function`, so a function-specific API key is required.
=> [IOPLT-530] Change authLevel to function

.github/workflows/release_infra.yaml
- Fix path that trigger the workflow
Before this commit, the workflow didn't run on changes on any files within the `infra/resources` directory.
After this commit the workflow runs on those changes.
=> [IOPLT-533] Fix path that triggers the workflow

.github/workflows/deploy_app_function.yaml, apps/functions-subscription/package.json
- Change reference of the dx workflow
- Add type `choice`, so the workflow shows multiple choices
- Update `build` script, generating code before compiling
We need to deploy the app function
=> [IOPLT-531] Fix Deploy App Function workflow

apps/functions-subscription/api/public.yaml
- Add the public.yaml file containing the api used by third-party services.
The system should provide access to certain APIs for third-party services.
Checked using [online swagger editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/pagopa/trial-system/features/add-get-subscription-external/apps/functions-subscription/api/public.yaml)
=> [IOPLT-536] Add the APIs used by third-party services

.changeset/tough-planes-behave.md, apps/functions-subscription/local.settings.json.example, apps/functions-subscription/package.json, apps/functions-subscription/src/adapters/azure/cosmosdb/__tests__/activation-request.test.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/activation-request.ts, apps/functions-subscription/src/adapters/ulid/__tests__/ulid.test.ts, apps/functions-subscription/src/adapters/ulid/monotonic-id.ts, apps/functions-subscription/src/domain/__tests__/data.ts, apps/functions-subscription/src/domain/__tests__/mocks.ts, apps/functions-subscription/src/domain/activation-request.ts, apps/functions-subscription/src/domain/capabilities.ts, apps/functions-subscription/src/domain/monotonic-id.ts, apps/functions-subscription/src/main.ts, apps/functions-subscription/src/use-cases/__tests__/process-subscription-request.test.ts, apps/functions-subscription/src/use-cases/process-subscription-request.ts, yarn.lock
Create the activation request in the `activations` container.
- Update the use case to make a call to persist the activation request
- Generate the activation request starting from the subscription
- Create an IdGenerator that generate a monotonic sort ordered id
We need to add the users that make subscription requests into the `activations` container.
Unit tests
=> [IOPLT-549] Create activation request

.changeset/sixty-pans-pretend.md, apps/functions-subscription/src/adapters/azure/cosmosdb/__tests__/subscription-history.test.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/subscription-history.ts, apps/functions-subscription/src/domain/__tests__/data.ts, apps/functions-subscription/src/main.ts, apps/functions-subscription/src/use-cases/__tests__/process-activation-request.test.ts, apps/functions-subscription/src/use-cases/process-activation-request.ts
- Update query of subscription-history getLatest
- Add a filter on activation request not active
- Rename leaseContainerPrefix of activationsConsumer
Fix issues
Unit test
=> Fix issues on activations change feed

apps/functions-subscription/src/use-cases/__tests__/get-subscription.test.ts, apps/functions-subscription/src/use-cases/get-subscription.ts
- Update the error message
The old error message showed an id that was misleading according to the input provided.
=> Change misleading error message

.changeset/rare-chairs-sparkle.md, apps/functions-subscription/src/adapters/azure/functions/__tests__/data.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/insert-subscription.test.ts, apps/functions-subscription/src/adapters/azure/functions/insert-subscription.ts, apps/functions-subscription/src/domain/subscription-history.ts, apps/functions-subscription/src/domain/subscription-request.ts, apps/functions-subscription/src/domain/subscription.ts, apps/functions-subscription/src/use-cases/__tests__/insert-subscription.test.ts, apps/functions-subscription/src/use-cases/get-subscription.ts, apps/functions-subscription/src/use-cases/insert-subscription.ts, apps/functions-subscription/src/use-cases/process-activation-request.ts
- Handle the `state` property when creating a new subscription
- If the state is passed, then create a subscription with the given state
- Refactor some functions, converting them into ReaderTaksEither
We want to have to possibility to create a subscription with a given state.
Unit tests
=> [IOPLT-568] Create a subscription providing a state

apps/functions-subscription/api/internal.yaml
- Add the OpenAPI spec to GET an activation job
We need a way to get the information of an activation job
Checking the output on editor.swagger.io
=> [IOPLT-569] Add GET activation job operation OpenAPI spec

.changeset/wet-beers-flash.md, apps/functions-subscription/api/internal.yaml, apps/functions-subscription/src/adapters/azure/cosmosdb/__tests__/activation-job.test.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/__tests__/activation-request.test.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/activation-job.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/activation-request.ts, apps/functions-subscription/src/domain/__tests__/activation-job.test.ts, apps/functions-subscription/src/domain/__tests__/data.ts, apps/functions-subscription/src/domain/activation-job.ts, apps/functions-subscription/src/main.ts
- Rename `/trials/{trialId}/activation-jobs` endpoint to `/trials/{trialId}/activation-job`
- Rename `GET /trials/{trialId}/activation-jobs/{id}` to `GET /trials/{trialId}/activation-job`
- Remove `ActivationJobId` from domain
- Force the value of id of activation-job to the trialId
The activation job is tied to the trialId, so to simplify the APIs and the code, we removed the `ActivationJobId` since it is the same as the `trialId`
Unit Test
=> Refactor activation-job

.changeset/fuzzy-lizards-run.md, apps/functions-subscription/src/adapters/azure/cosmosdb/__tests__/activation-job.test.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/activation-job.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/data.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/get-activation-job.test.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/mocks.ts, apps/functions-subscription/src/adapters/azure/functions/codec.ts, apps/functions-subscription/src/adapters/azure/functions/get-activation-job.ts, apps/functions-subscription/src/adapters/azure/functions/insert-activation-job.ts, apps/functions-subscription/src/domain/__tests__/activation-job.test.ts, apps/functions-subscription/src/domain/__tests__/data.ts, apps/functions-subscription/src/domain/__tests__/mocks.ts, apps/functions-subscription/src/domain/activation-job.ts, apps/functions-subscription/src/domain/capabilities.ts, apps/functions-subscription/src/main.ts, apps/functions-subscription/src/system-env.ts
- Implement the handler to get an activation job
- Create the ActivationJobReader
- Implement the `get` operation to retrieve the activation job
We need a way to get the information about an activation job.
Unit tests.
=> [IOPLT-571] Implement get activation job

.changeset/dry-kids-clap.md, apps/functions-subscription/api/internal.yaml, apps/functions-subscription/src/adapters/azure/cosmosdb/__tests__/activation-job.test.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/activation-job.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/errors.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/data.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/mocks.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/update-activation-job.test.ts, apps/functions-subscription/src/adapters/azure/functions/codec.ts, apps/functions-subscription/src/adapters/azure/functions/update-activation-job.ts, apps/functions-subscription/src/domain/__tests__/activation-job.test.ts, apps/functions-subscription/src/domain/activation-job.ts, apps/functions-subscription/src/main.ts, apps/functions-subscription/src/system-env.ts
- Define activation job update endpoint
- Add activation job update handler
- Add activation job update to `ActivationJobWriter`
- Add activation job update implementation
- Replace `NonNegativeNumber` with `NonNegativeInteger`
The system must allow increasing the number of active users for a trial
Unit Test
=> [IOPLT-570] Add update activation job

.changeset/empty-nails-design.md, apps/functions-subscription/src/domain/__tests__/activation-job.test.ts, apps/functions-subscription/src/domain/__tests__/data.ts, apps/functions-subscription/src/domain/activation-job.ts, apps/functions-subscription/src/domain/subscription.ts
- Remove `createdAt` from the `ActivationJob` object
- Remove `activatedAt` from `Subscription` and `SubscriptionHistory`
We cleaned up the domain objects, removing unused properties that are not exposed through the API.
Unit tests.
=> Remove unused fields

apps/functions-subscription/src/adapters/azure/cosmosdb/__tests__/activation-request.test.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/activation-request.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/decode.ts, apps/functions-subscription/src/adapters/azure/functions/get-subscription.ts, apps/functions-subscription/src/domain/__tests__/mocks.ts, apps/functions-subscription/src/domain/activation-request.ts, apps/functions-subscription/src/domain/capabilities.ts, apps/functions-subscription/src/main.ts, apps/functions-subscription/src/use-cases/__tests__/process-activation-job.test.ts, apps/functions-subscription/src/use-cases/__tests__/process-subscription-request.test.ts, apps/functions-subscription/src/use-cases/process-activation-job.ts, apps/functions-subscription/src/use-cases/process-subscription-request.ts
- Use a custom codec when parsing
- Uniform the way to access to the data
- Remove the `Repository` in favour of `Reader` and `Writer`
- Move the generic type as close as possible to the function who uses it
Unit tests
=> Reduce tech debt

apps/functions-subscription/src/adapters/azure/cosmosdb/activation-request.ts, apps/functions-subscription/src/domain/activation-request.ts
- Add `ORDER BY` on list activation-request query
- Rename `elementsToFetch` to `limit`
None, results are already ordered by ID becaseu there is no ambiguity about which index to use. However, making the order explicit makes it more robust toward the the number of indexes.
Run the query locally
=> Update activation-request list

.github/workflows/code_review.yaml
- Add `yarn.lock` file to `paths` section of the GitHub Action
We need to verify the PR created by dependabot are passing the checks of our CI
=> [IOPLT-555] Execute workflow also on lockfile changes

apps/functions-subscription/api/internal.yaml
- Add the `POST /trials` to permit the creation of a trial
We need to create a trial through API
Using the Swagger editor at editor.swagger.io
=> [IOPLT-447] Add `POST /trials` to OpenAPI specification

.changeset/great-bugs-tie.md, apps/functions-subscription/api/internal.yaml, apps/functions-subscription/src/adapters/azure/servicebus/__tests__/event.test.ts, apps/functions-subscription/src/adapters/azure/servicebus/event.ts
- Replace `$ref` with object definition
The generator generates an empty object if it is defined using `$ref`.
Unit Test
=> [IOPLT-586] - Fix SubscriptionEvent openapi definition

.changeset/hot-boats-hide.md, apps/functions-subscription/src/use-cases/__tests__/create-subscription.test.ts, apps/functions-subscription/src/use-cases/create-subscription.ts, vitest.config.ts
- Add check about trial existence on subscription creation
- Update vitest.config.js
A subscription should be created only if the trial exists
Unit Tests
=> [IOPLT-610] - Add trial existence check

.github/opex_filters.yaml, .github/workflows/call_opex_api.yml, .github/workflows/call_pr_opex_api.yml, .github/workflows/opex_api_trial.yaml, .github/workflows/pr_opex_api_trial.yaml, apps/functions-subscription/.opex/management/env/prod/backend.ini, apps/functions-subscription/.opex/management/env/prod/backend.tfvars, apps/functions-subscription/.opex/management/env/prod/config.yaml, apps/functions-subscription/.opex/management/env/prod/terraform.tfvars
=> [#IOPLT-618] Add Opex dashboard pipelines

apps/functions-subscription/api/internal.yaml
- Change server's URL
The app function has been renamed
=> Update Trial System API URL

.github/workflows/code_review_infra.yaml, .github/workflows/release_infra.yaml
- Add `terraform` group to GitHub Actions that are using Terraform
When executing multiple Actions, we do not want to cancel ongoing Actions if a new one is going to start.
This could led to issues with Terraform state file.
=> Add concurrency block on GitHub Actions using terraform

.github/workflows/pr_title_linter_and_linker.yaml
- Add branches-ignore on pr_title_linter_and_linker workflow
The `pr_title_linter_and_linker` workflow should not run on PR created by Changesets
N/A
=> Add branches-ignore on pr_title_linter_and_linker

.changeset/cool-pens-kneel.md, apps/functions-subscription/src/use-cases/__tests__/process-activation-job.test.ts, apps/functions-subscription/src/use-cases/process-activation-job.ts
- Change activation job processing function
Currently, the system raises an error during the activation job handling if no slots are available. After this PR, the system will handle the job without errors.
Unit Test
=> [IOPLT-646] Fix issue on activation job processing function

.changeset/shiny-games-appear.md, scripts/ops-scripts/package.json, scripts/ops-scripts/src/migrate-activations.ts, yarn.lock
Depends on #161 
- Add a new migration script
We have to migrate the items from a cosmos container to another.
Tested locally.
=> [IOPLT-656] Add migration script

.changeset/big-kids-guess.md, scripts/ops-scripts/package.json, scripts/ops-scripts/src/remove-documents.ts
- Add a script to remove trial's subscriptions and subscriptions-history of load tests.
We conducted some load tests and need to remove the subscriptions and subscription history created by these tests.
Locally
=> [IOPLT-627] Add script to remove trial's subs and subs-history of load tests

.changeset/tiny-penguins-sit.md, apps/functions-subscription/package.json, yarn.lock
- Bump `@azure/functions` package to `4.5.1`
With the old version of that package, the `retry` options were ignored.
>[!NOTE]
> The [bug has been fixed in version `4.5.0`](https://github.com/Azure/azure-functions-nodejs-library/releases/tag/v4.5.0) which includes [this PR](https://github.com/Azure/azure-functions-nodejs-library/pull/250).
=> [IOPLT-681] Bump `@azure/functions` package

.github/workflows/release_infra.yaml
- Change trigger of GitHub actions
We want to automate the release of the infrastructure.
The release should be triggered when a tag is created.
> [!WARNING]
> To let this PR work, we need to close those PRs this depends on: #196 #198
=> [IOPLT-701] Change GitHub Action trigger to push tags

.github/workflows/release.yaml
- Configure Git user before changeset
> [!NOTE]
> The consequence of this is that every commit will be authored by the value provided (in this case by the trial-system-github-bot).
=> [IOPLT-680] Configure Git user before running Changeset action

.changeset/honest-cherries-smile.md, scripts/k6-load-test/package.json, scripts/k6-load-test/webpack.config.js, yarn.lock
This PR should close #185
- Bump `webpack` to current latest version
- Bump `webpack-cli` to current latest version
The version used has a vulnerability we need to fix.
=> Upgrade `webpack` and `webpack-cli`

.changeset/tiny-singers-serve.md, apps/functions-subscription/src/adapters/azure/functions/__tests__/create-trial.test.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/data.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/get-activation-job.test.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/get-subscription.test.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/update-activation-job.test.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/update-subscription.test.ts
- Add missing HTTP headers
To have stronger unit tests, we are adding the missing information into the HTTP requests generated during the tests.
=> [IOPLT-731] Add missing headers to HTTP request on unit tests

.changeset/nine-dolphins-rule.md, apps/functions-subscription/src/adapters/azure/functions/__tests__/middleware.test.ts, apps/functions-subscription/src/adapters/azure/functions/middleware.ts, apps/functions-subscription/src/domain/users.ts
- Add new middleware that get user information and authorize it
We are introducing the multy-tenancy
Unit tests
=> [IOPLT-730] Add new middleware

scripts/ops-scripts/bin/trial-activate.sh
=> [#IOPLT-733] Add Bash script for massive activation from csv

.changeset/polite-tools-hug.md, scripts/ops-scripts/.env.example, scripts/ops-scripts/package.json, scripts/ops-scripts/src/migrate-trials.ts
- Create a script to migrate the trials adding the new `ownerId` property
=> [IOPLT-737] Create script to migrate trials

.changeset/wise-parrots-remain.md, apps/functions-subscription/src/adapters/azure/functions/__tests__/get-trial.test.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/insert-subscription.test.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/middleware.test.ts, apps/functions-subscription/src/adapters/azure/functions/create-trial.ts, apps/functions-subscription/src/adapters/azure/functions/get-activation-job.ts, apps/functions-subscription/src/adapters/azure/functions/get-subscription.ts, apps/functions-subscription/src/adapters/azure/functions/get-trial.ts, apps/functions-subscription/src/adapters/azure/functions/insert-subscription.ts, apps/functions-subscription/src/adapters/azure/functions/middleware.ts, apps/functions-subscription/src/adapters/azure/functions/update-activation-job.ts, apps/functions-subscription/src/adapters/azure/functions/update-subscription.ts
- Replace legacy middleware
- Fix some unit tests
- Remove legacy middleware and its unit tests
We need to pass the user's information to the underlying layers
Unit tests
=> [IOPLT-739] Replace authorization middleware

.changeset/fast-years-study.md, apps/functions-subscription/local.settings.json.example, apps/functions-subscription/src/adapters/azure/cosmosdb/__tests__/trial.test.ts, apps/functions-subscription/src/adapters/azure/cosmosdb/trial.ts
- Modify `get` function; migrate from point read
> [!NOTE]
> We are migrating from point read to query, because we changed the container and we also changed the partition key.
> Without this PR, we do not find the elements, because the partition key in the new container is changed.
> We will come back to the point read soon, after the migration.
=> [IOPLT-750] Convert from point read to query

.changeset/shaggy-vans-serve.md, apps/functions-subscription/src/adapters/azure/functions/__tests__/data.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/get-activation-job.test.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/insert-subscription.test.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/update-activation-job.test.ts, apps/functions-subscription/src/adapters/azure/functions/__tests__/update-subscription.test.ts, apps/functions-subscription/src/adapters/azure/functions/get-activation-job.ts, apps/functions-subscription/src/adapters/azure/functions/get-subscription.ts, apps/functions-subscription/src/adapters/azure/functions/update-activation-job.ts, apps/functions-subscription/src/adapters/azure/functions/update-subscription.ts, apps/functions-subscription/src/domain/__tests__/trial.test.ts, apps/functions-subscription/src/domain/trial.ts, apps/functions-subscription/src/system-env.ts, apps/functions-subscription/src/use-cases/__tests__/get-activation-job.test.ts, apps/functions-subscription/src/use-cases/__tests__/get-subscription.test.ts, apps/functions-subscription/src/use-cases/__tests__/update-activation-job.test.ts, apps/functions-subscription/src/use-cases/__tests__/update-subscription.test.ts, apps/functions-subscription/src/use-cases/get-activation-job.ts, apps/functions-subscription/src/use-cases/get-subscription.ts, apps/functions-subscription/src/use-cases/update-activation-job.ts, apps/functions-subscription/src/use-cases/update-subscription.ts
- Authorize `updateActivationJob` operation
- Authorize `getActivationJob` operation
- Authorize `getSubscription` operation
- Authorize `updateSubscription` operation
When the trial owner is making an operation that involves a trial, we need to make sure that owner can operate only on its trial.
Update unit tests accordingly
=> [IOPLT-767] Add authorization on missing endpoints

.changeset/ninety-dolls-cough.md, apps/functions-subscription/src/adapters/azure/functions/middleware.ts
- Add ApiTrialSupport group to the AllowedGroup type
This is needed to effectively use the new group type on endpoints.
=> [IOPLT-772] Add ApiTrialSupport to AllowedGroup type.

.changeset/famous-houses-invent.md, apps/functions-subscription/src/adapters/azure/functions/middleware.ts, apps/functions-subscription/src/domain/users.ts
- Add `Support` tenant
This change is needed to handle the support Tenant in #256
=> [IOPLT-774] Add `Support` tenant
